# Generated by Django 6.1 on 2026-09-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('VACCINATION', 'Vaccination'), ('TREATMENT', 'Treatment'), ('ILLNESS', 'Illness'), ('VET_VISIT', 'Veterinary Visit'), ('OTHER', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('medication', models.CharField(blank=True, max_length=200)),
                ('veterinarian', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='livestock.animal')),
            ],
        ),
    ]
