# Generated by Django 6.1 on 2026-09-02 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_healthrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField()),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('actual_birth_date', models.DateField(blank=True, null=True)),
                ('offspring_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('PREGNANT', 'Pregnant'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('BORN', 'Birth Recorded')], default='PLANNED', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records_as_female', to='livestock.animal')),
                ('male', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeding_records_as_male', to='livestock.animal')),
            ],
        ),
    ]
