# Generated by Django 6.1 on 2026-09-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_breedingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(choices=[('MILK', 'Milk'), ('WEIGHT', 'Weight'), ('MEAT', 'Meat'), ('OTHER', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='livestock.animal')),
            ],
        ),
    ]
