# Generated by Django 6.1 on 2026-09-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_productionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('ANIMAL_SALE', 'Animal Sale'), ('MILK_SALE', 'Milk Sale'), ('MEAT_SALE', 'Meat Sale'), ('OTHER_INCOME', 'Other Income'), ('FEED', 'Feed'), ('MEDICINE', 'Medicine'), ('VETERINARY', 'Veterinary'), ('LABOUR', 'Labour'), ('EQUIPMENT', 'Equipment'), ('TRANSPORT', 'Transport'), ('OTHER_EXPENSE', 'Other Expense')], max_length=30)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='livestock.animal')),
            ],
        ),
    ]
