# Generated by Django 6.1 on 2026-09-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_farmsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
